version: "3"

services:
  vite:
    build:
        context: .
        dockerfile: ./docker/vite/Dockerfile
    ports:
      - '${VITE_PORT:-8080}:${VITE_PORT:-8080}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    command: ng serve --port ${VITE_PORT:-8080} --host 0.0.0.0 --poll 200
